/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TImageData } from "./types";
export { TImageData } from "./types";
export namespace Components {
    interface DaisyCard {
        "heading"?: string;
    }
    interface ImageCarousel {
        "imageDataGroup": TImageData[];
    }
    interface RootComponent {
    }
}
declare global {
    interface HTMLDaisyCardElement extends Components.DaisyCard, HTMLStencilElement {
    }
    var HTMLDaisyCardElement: {
        prototype: HTMLDaisyCardElement;
        new (): HTMLDaisyCardElement;
    };
    interface HTMLImageCarouselElement extends Components.ImageCarousel, HTMLStencilElement {
    }
    var HTMLImageCarouselElement: {
        prototype: HTMLImageCarouselElement;
        new (): HTMLImageCarouselElement;
    };
    interface HTMLRootComponentElement extends Components.RootComponent, HTMLStencilElement {
    }
    var HTMLRootComponentElement: {
        prototype: HTMLRootComponentElement;
        new (): HTMLRootComponentElement;
    };
    interface HTMLElementTagNameMap {
        "daisy-card": HTMLDaisyCardElement;
        "image-carousel": HTMLImageCarouselElement;
        "root-component": HTMLRootComponentElement;
    }
}
declare namespace LocalJSX {
    interface DaisyCard {
        "heading"?: string;
    }
    interface ImageCarousel {
        "imageDataGroup": TImageData[];
    }
    interface RootComponent {
    }
    interface IntrinsicElements {
        "daisy-card": DaisyCard;
        "image-carousel": ImageCarousel;
        "root-component": RootComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "daisy-card": LocalJSX.DaisyCard & JSXBase.HTMLAttributes<HTMLDaisyCardElement>;
            "image-carousel": LocalJSX.ImageCarousel & JSXBase.HTMLAttributes<HTMLImageCarouselElement>;
            "root-component": LocalJSX.RootComponent & JSXBase.HTMLAttributes<HTMLRootComponentElement>;
        }
    }
}
