/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DaisyCard {
        "heading"?: string;
    }
    interface DaisyCardLayout {
    }
    interface RootComponent {
    }
}
declare global {
    interface HTMLDaisyCardElement extends Components.DaisyCard, HTMLStencilElement {
    }
    var HTMLDaisyCardElement: {
        prototype: HTMLDaisyCardElement;
        new (): HTMLDaisyCardElement;
    };
    interface HTMLDaisyCardLayoutElement extends Components.DaisyCardLayout, HTMLStencilElement {
    }
    var HTMLDaisyCardLayoutElement: {
        prototype: HTMLDaisyCardLayoutElement;
        new (): HTMLDaisyCardLayoutElement;
    };
    interface HTMLRootComponentElement extends Components.RootComponent, HTMLStencilElement {
    }
    var HTMLRootComponentElement: {
        prototype: HTMLRootComponentElement;
        new (): HTMLRootComponentElement;
    };
    interface HTMLElementTagNameMap {
        "daisy-card": HTMLDaisyCardElement;
        "daisy-card-layout": HTMLDaisyCardLayoutElement;
        "root-component": HTMLRootComponentElement;
    }
}
declare namespace LocalJSX {
    interface DaisyCard {
        "heading"?: string;
    }
    interface DaisyCardLayout {
    }
    interface RootComponent {
    }
    interface IntrinsicElements {
        "daisy-card": DaisyCard;
        "daisy-card-layout": DaisyCardLayout;
        "root-component": RootComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "daisy-card": LocalJSX.DaisyCard & JSXBase.HTMLAttributes<HTMLDaisyCardElement>;
            "daisy-card-layout": LocalJSX.DaisyCardLayout & JSXBase.HTMLAttributes<HTMLDaisyCardLayoutElement>;
            "root-component": LocalJSX.RootComponent & JSXBase.HTMLAttributes<HTMLRootComponentElement>;
        }
    }
}
